version: '3.8'

services:
  laravel:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: