# Imagen base con Node LTS sobre Debian 12 (bookworm), más moderna que bullseye
FROM node:20-bookworm

# Instala utilidades básicas + libstdc++6 (y build-essential por si hay addons nativos)
RUN apt-get update && apt-get install -y \
    git \
    curl \
    less \
    bash-completion \
    build-essential \
    libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

# Carpeta de trabajo
WORKDIR /workspace

# Si quieres aprovechar la caché de npm, descomenta esto y ajusta:
# COPY package*.json ./
# RUN npm install

# Angular CLI lo sigues instalando en postCreateCommand del devcontainer.json
# (o aquí si algún día prefieres dejarlo fijo)

CMD [ "bash" ]